package com.heiliuer.fuda_zaoan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SignRecord".
 */
public class SignRecord {

    private Long id;
    private Long createTime;
    private Long signTime;
    private Boolean success;
    private Boolean autoSigned;
    private String signDate;
    private String logJson;

    public SignRecord() {
    }

    public SignRecord(Long id) {
        this.id = id;
    }

    public SignRecord(Long id, Long createTime, Long signTime, Boolean success, Boolean autoSigned, String signDate, String logJson) {
        this.id = id;
        this.createTime = createTime;
        this.signTime = signTime;
        this.success = success;
        this.autoSigned = autoSigned;
        this.signDate = signDate;
        this.logJson = logJson;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getSignTime() {
        return signTime;
    }

    public void setSignTime(Long signTime) {
        this.signTime = signTime;
    }

    public Boolean getSuccess() {
        return success;
    }

    public void setSuccess(Boolean success) {
        this.success = success;
    }

    public Boolean getAutoSigned() {
        return autoSigned;
    }

    public void setAutoSigned(Boolean autoSigned) {
        this.autoSigned = autoSigned;
    }

    public String getSignDate() {
        return signDate;
    }

    public void setSignDate(String signDate) {
        this.signDate = signDate;
    }

    public String getLogJson() {
        return logJson;
    }

    public void setLogJson(String logJson) {
        this.logJson = logJson;
    }

}
