package com.heiliuer.fuda_zaoan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.heiliuer.fuda_zaoan.SignRecord;

import com.heiliuer.fuda_zaoan.dao.SignRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig signRecordDaoConfig;

    private final SignRecordDao signRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        signRecordDaoConfig = daoConfigMap.get(SignRecordDao.class).clone();
        signRecordDaoConfig.initIdentityScope(type);

        signRecordDao = new SignRecordDao(signRecordDaoConfig, this);

        registerDao(SignRecord.class, signRecordDao);
    }
    
    public void clear() {
        signRecordDaoConfig.getIdentityScope().clear();
    }

    public SignRecordDao getSignRecordDao() {
        return signRecordDao;
    }

}
